import Link from "next/link";
import { ChevronRight, LockKeyhole, Play } from "lucide-react";
import { notFound } from "next/navigation";

import { ilkQadamRoadmap } from "@/data/courses/ilk-qadam";
import { isLocale, type Locale } from "@/lib/i18n";

export default async function IlkQadamRoadmap({ params }: { params: Promise<{ locale: string }> }) {
  const { locale: rawLocale } = await params; if (!isLocale(rawLocale)) notFound(); const locale = rawLocale as Locale;
  const heading = locale === "uz" ? "Ilk qadam" : locale === "en" ? "First Steps" : "Первые шаги";
  return <main className="mx-auto max-w-5xl px-4 py-12 sm:px-6 lg:px-8"><p className="font-mono text-[11px] uppercase tracking-[.16em] text-primary">78 lessons · 5 quarters</p><h1 className="mt-4 text-4xl font-semibold tracking-[-.05em] sm:text-5xl">{heading}</h1><p className="mt-5 max-w-2xl leading-7 text-muted-foreground">{locale === "uz" ? "Hayotiy savol → simulyatsiya → formula → kasb → quiz va laboratoriya." : locale === "en" ? "Real question → simulation → formula → career → quiz and lab." : "Жизненный вопрос → симуляция → формула → профессия → квиз и лаборатория."}</p><div className="mt-10 space-y-4">{ilkQadamRoadmap.map((quarter) => <details key={quarter.number} open={quarter.number === 1} className="group rounded-[2rem] border border-border bg-card"><summary className="flex min-h-20 cursor-pointer list-none items-center justify-between px-6"><div><p className="font-mono text-[10px] uppercase tracking-wider text-primary">{locale === "uz" ? `${quarter.number}-chorak` : locale === "en" ? `Quarter ${quarter.number}` : `${quarter.number}-я четверть`}</p><h2 className="mt-1 text-xl font-semibold">{quarter.title}</h2></div><ChevronRight className="size-5 transition-transform group-open:rotate-90"/></summary><div className="border-t border-border p-3">{quarter.lessons.map((lesson) => { const active = lesson.id === 1; const item = <div className="flex min-h-16 items-center gap-4 rounded-2xl px-4 transition-colors hover:bg-muted"><span className="w-7 font-mono text-xs text-muted-foreground">{String(lesson.id).padStart(2, "0")}</span><span className="flex-1 text-sm leading-5">{lesson.title}</span>{active ? <Play className="size-4 text-primary"/> : <LockKeyhole className="size-4 text-muted-foreground"/>}</div>; return active ? <Link key={lesson.id} href={`/${locale}/learn/ilk-qadam/01`}>{item}</Link> : <div key={lesson.id} aria-disabled="true">{item}</div>; })}</div></details>)}</div></main>;
}
